### ISSUE TITLE
Copia profonda del Jgraph

### ISSUE THREAD

**Issue by ScrappyCocco** [NicoloTartaggia/7DOS-plugin#20]
Avevo messo come il metodo sopra `Object.assign`, WebStorm mi ha suggerito questo formato.
Tuttavia sembra non andare, in quanto non effettua la copia profonda, si nota facilmente dal panel, visto che cliccando su un nodo del grafico fa l'observe sulla nostra rete e non su una finta di copia

https://github.com/NicoloTartaggia/7DOS-plugin/blob/d2cec0e5f7ba658695edeb182ccf4e31438d89c6/src/core/network/adapter/ConcreteNetworkAdapter.ts#L108

**Comment by UdrK** [comment]
Dovrebbe essere a posto, bisogna controllare però

**Comment by ScrappyCocco** [comment]
Fatta con una libreria di clone
